=== dreedyman/Elastic-Grid/modules/elastic-grid-model/src/main/conf/binding.xsd
<?xml version='1.0' encoding='UTF-8'?>
<!--

    Copyright (C) 2007-2008 Elastic Grid, LLC.
    
    Licensed under the GNU Lesser General Public License, Version 3.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
            http://www.gnu.org/licenses/lgpl-3.0.html
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="binding">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="namespace" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="mapping" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>

            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="direction" type="xs:string"/>
            <xs:attribute name="forwards" type="xs:boolean"/>
            <xs:attribute name="package" type="xs:string"/>
            <xs:attribute name="track-source" type="xs:boolean"/>
            <xs:attribute name="force-classes" type="xs:boolean"/>

            <xs:attributeGroup ref="style"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="include">
        <xs:complexType>
            <xs:attribute name="path" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="collection">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="value"/>
                <xs:element ref="structure"/>
                <xs:element ref="collection"/>
            </xs:choice>

            <xs:attribute name="load-method" type="xs:string"/>
            <xs:attribute name="size-method" type="xs:string"/>
            <xs:attribute name="store-method" type="xs:string"/>
            <xs:attribute name="add-method" type="xs:string"/>
            <xs:attribute name="iter-method" type="xs:string"/>
            <xs:attribute name="item-type" type="xs:string"/>

            <xs:attributeGroup ref="style"/>
            <xs:attributeGroup ref="name"/>
            <xs:attributeGroup ref="object"/>
            <xs:attributeGroup ref="property"/>
            <xs:attributeGroup ref="structure"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="format">
        <xs:complexType>

            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="type" use="required" type="xs:string"/>

            <xs:attributeGroup ref="string"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="namespace" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="mapping" minOccurs="0" maxOccurs="unbounded"/>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="value"/>
                    <xs:element ref="structure"/>
                    <xs:element ref="collection"/>
                </xs:choice>
            </xs:sequence>

            <xs:attribute name="class" use="required" type="xs:string"/>
            <xs:attribute name="abstract" type="xs:boolean"/>
            <xs:attribute name="extends" type="xs:string"/>
            <xs:attribute name="type-name" type="xs:string"/>

            <xs:attributeGroup ref="style"/>
            <xs:attributeGroup ref="name"/>
            <xs:attributeGroup ref="object"/>
            <xs:attributeGroup ref="structure"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="namespace">
        <xs:complexType>
            <xs:attribute name="uri" use="required" type="xs:string"/>
            <xs:attribute name="prefix" type="xs:string"/>
            <xs:attribute name="default" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="structure">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="value"/>
                <xs:element ref="structure"/>
                <xs:element ref="collection"/>
            </xs:choice>

            <xs:attribute name="map-as" type="xs:string"/>

            <xs:attributeGroup ref="style"/>
            <xs:attributeGroup ref="name"/>
            <xs:attributeGroup ref="object"/>
            <xs:attributeGroup ref="property"/>
            <xs:attributeGroup ref="structure"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="value">
        <xs:complexType>

            <xs:attribute name="constant" type="xs:string"/>
            <xs:attribute name="format" type="xs:string"/>
            <xs:attribute name="ident" type="xs:string"/>
            <xs:attribute name="style" type="xs:string"/>

            <xs:attributeGroup ref="name"/>
            <xs:attributeGroup ref="property"/>
            <xs:attributeGroup ref="string"/>

        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="style">
        <xs:attribute name="value-style" type="xs:string"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="name">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="ns" type="xs:string"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="property">
        <xs:attribute name="field" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="usage" type="xs:string"/>
        <xs:attribute name="test-method" type="xs:string"/>
        <xs:attribute name="get-method" type="xs:string"/>
        <xs:attribute name="set-method" type="xs:string"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="structure">
        <xs:attribute name="label" type="xs:string"/>
        <xs:attribute name="using" type="xs:string"/>
        <xs:attribute name="ordered" type="xs:boolean"/>
        <xs:attribute name="choice" type="xs:boolean"/>
        <xs:attribute name="flexible" type="xs:boolean"/>
        <xs:attribute name="allow-repeats" type="xs:boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="string">
        <xs:attribute name="default" type="xs:string"/>
        <xs:attribute name="serializer" type="xs:string"/>
        <xs:attribute name="deserializer" type="xs:string"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="object">
        <xs:attribute name="factory" type="xs:string"/>
        <xs:attribute name="pre-set" type="xs:string"/>
        <xs:attribute name="post-set" type="xs:string"/>
        <xs:attribute name="pre-get" type="xs:string"/>
        <xs:attribute name="marshaller" type="xs:string"/>
        <xs:attribute name="unmarshaller" type="xs:string"/>
    </xs:attributeGroup>

</xs:schema>

=== dreedyman/Elastic-Grid/modules/elastic-grid-model/src/main/conf/binding-REST.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Elastic Grid
    Copyright (C) 2008-2009 Elastic Grid, LLC.
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
    
    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<binding name="ElasticGridREST"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="binding.xsd">

    <namespace prefix="eg"  uri="urn:elastic-grid:eg" default="elements"/>
    <namespace prefix="ec2" uri="urn:elastic-grid:ec2" default="none"/>
    <namespace prefix="lan" uri="urn:elastic-grid:lan" default="none"/>

    <format type="java.net.InetAddress"
            serializer="com.elasticgrid.model.internal.jibx.Conversion.serializeInetAddress"
            deserializer="com.elasticgrid.model.internal.jibx.Conversion.deserializeInetAddress"/>

    <format type="com.elasticgrid.model.NodeProfile"
            serializer="com.elasticgrid.model.internal.jibx.Conversion.serializeNodeProfile"
            deserializer="com.elasticgrid.model.internal.jibx.Conversion.deserializeNodeProfile"/>

    <mapping name="clusters" class="com.elasticgrid.model.internal.Clusters">
        <collection field="clusters"/>
    </mapping>
    <mapping name="applications" class="com.elasticgrid.model.internal.Applications">
        <collection field="applications"/>
    </mapping>

    <mapping class="com.elasticgrid.model.internal.AbstractCluster" abstract="true">
        <value name="name" field="name" style="attribute"/>
        <!--<value name="href" field="name" style="attribute"/>-->
        <collection field="applications"/>
    </mapping>
    <mapping name="cluster" ns="urn:elastic-grid:ec2"
             class="com.elasticgrid.model.ec2.impl.EC2ClusterImpl" extends="com.elasticgrid.model.internal.AbstractCluster">
        <structure map-as="com.elasticgrid.model.internal.AbstractCluster"/>
        <collection get-method="getNodes" set-method="setNodes"
                    item-type="com.elasticgrid.model.ec2.impl.EC2NodeImpl"
                    factory="com.elasticgrid.model.internal.AbstractCluster.setOfNodes"/>
    </mapping>
    <mapping name="cluster" ns="urn:elastic-grid:lan"
             class="com.elasticgrid.model.lan.impl.LANClusterImpl" extends="com.elasticgrid.model.internal.AbstractCluster">
        <structure map-as="com.elasticgrid.model.internal.AbstractCluster"/>
        <collection get-method="getNodes" set-method="setNodes"
                    item-type="com.elasticgrid.model.lan.impl.LANNodeImpl"
                    factory="com.elasticgrid.model.internal.AbstractCluster.setOfNodes"/>
    </mapping>

    <mapping name="cluster-provisioning" class="com.elasticgrid.model.ClusterProvisioning">
        <value name="name" field="clusterName" style="attribute"/>
        <value name="monitors" field="numberOfMonitors"/>
        <value name="agents" field="numberOfAgents"/>
    </mapping>

    <mapping class="com.elasticgrid.model.internal.AbstractNode" abstract="true">
        <value name="profile" field="profile" style="attribute"/>
        <value field="address" style="text"/>
    </mapping>
    <mapping name="node" ns="urn:elastic-grid:ec2"
             class="com.elasticgrid.model.ec2.impl.EC2NodeImpl" extends="com.elasticgrid.model.internal.AbstractNode">
        <structure map-as="com.elasticgrid.model.internal.AbstractNode"/>
        <value name="id" field="instanceID" style="attribute"/>
    </mapping>
    <mapping name="node" ns="urn:elastic-grid:lan"
             class="com.elasticgrid.model.lan.impl.LANNodeImpl" extends="com.elasticgrid.model.internal.AbstractNode">
        <value name="id" field="instanceID" style="attribute"/>
        <structure map-as="com.elasticgrid.model.internal.AbstractNode"/>
    </mapping>

    <mapping name="application" class="com.elasticgrid.model.internal.ApplicationImpl">
        <value name="name" field="name" style="attribute"/>
        <collection field="services" item-type="com.elasticgrid.model.internal.ServiceImpl"/>
    </mapping>

    <mapping name="service" class="com.elasticgrid.model.internal.ServiceImpl">
        <value name="name" field="name" style="attribute"/>
    </mapping>

</binding>

=== dreedyman/Elastic-Grid/modules/elastic-grid-model/src/main/conf/binding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Elastic Grid
    Copyright (C) 2008-2010 Elastic Grid, LLC.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<binding name="ElasticGrid"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="binding.xsd">

    <namespace uri="http://aws.amazon.com/s3" prefix="s3"/>

    <format type="java.net.InetAddress"
            serializer="com.elasticgrid.model.internal.jibx.Conversion.serializeInetAddress"
            deserializer="com.elasticgrid.model.internal.jibx.Conversion.deserializeInetAddress"/>

    <mapping name="local-repository" class="com.elasticgrid.model.internal.LocalStore"
             extends="com.elasticgrid.model.internal.AbstractStore">
        <structure map-as="com.elasticgrid.model.internal.AbstractStore"/>
    </mapping>
    <mapping name="remote-repository" class="com.elasticgrid.model.internal.RemoteStore"
             extends="com.elasticgrid.model.internal.AbstractStore">
        <value name="s3:bucket" constant="1234"/>
        <structure map-as="com.elasticgrid.model.internal.AbstractStore"/>
    </mapping>

    <mapping class="com.elasticgrid.model.internal.AbstractStore" abstract="true">
        <collection name="clusters" field="clusters" item-type="java.lang.String" usage="optional"
                    factory="com.elasticgrid.model.internal.AbstractStore.setOfClusters">
            <structure name="cluster">
                <value name="name" style="attribute"/>
            </structure>
        </collection>
        <collection name="applications" field="applications" item-type="java.lang.String" usage="optional"
                    factory="com.elasticgrid.model.internal.AbstractStore.setOfApplications">
            <structure name="application">
                <value name="name" style="attribute"/>
            </structure>
        </collection>
    </mapping>

    <mapping class="com.elasticgrid.model.internal.AbstractCluster" abstract="true">
        <value name="name" field="name" style="attribute"/>
        <collection name="applications" field="applications"
                    item-type="com.elasticgrid.model.internal.ApplicationImpl"
                    factory="com.elasticgrid.model.internal.Factories.listOfApplications"/>
    </mapping>
    <mapping name="cluster" class="com.elasticgrid.model.ec2.impl.EC2ClusterImpl" extends="com.elasticgrid.model.internal.AbstractCluster">
        <namespace prefix="ec2" uri="http://aws.amazon.com/ec2" default="elements"/>
        <structure map-as="com.elasticgrid.model.internal.AbstractCluster"/>
        <collection name="nodes" get-method="getNodes" set-method="setNodes"
                    item-type="com.elasticgrid.model.ec2.impl.EC2NodeImpl"
                    factory="com.elasticgrid.model.internal.AbstractCluster.setOfNodes"/>
    </mapping>

    <mapping class="com.elasticgrid.model.internal.AbstractNode" abstract="true">
        <value name="address" field="address"/>
    </mapping>
    <mapping name="node" class="com.elasticgrid.model.ec2.impl.EC2NodeImpl" extends="com.elasticgrid.model.internal.AbstractNode">
        <namespace prefix="ec2" uri="http://aws.amazon.com/ec2" default="elements"/>
        <structure map-as="com.elasticgrid.model.internal.AbstractNode"/>
        <value name="instanceID" field="instanceID"/>
    </mapping>

    <mapping name="application" class="com.elasticgrid.model.internal.ApplicationImpl">
        <value name="name" field="name" style="attribute"/>
    </mapping>

</binding>
